language: emacs-lisp

env:
  matrix:
    # - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1

install:
  # Emacs
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  # Cask
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask install
script:
  - make travis
